showme_project/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users/:id', to: 'users#show'

  get 'users', to: 'users#index'

  put 'users/:id', to: 'users#update'

  delete 'users/:id', to: 'users#destroy'

  get 'articles/approve', to: 'articles#approveindex'

  put 'articles/approve/:id', to: 'articles#approveupdate'


  resources :articles

  root "static#home"

end

showme_project/app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
    # articles belong to the user

	validates :title, :description, :git_link, :difficulty, :user_id, presence: true
    # validates that the above attributes have input values
	validates :title , length: { minimum: 2, maximum: 256, message: "must be between 2 and 256 characters long!" }
    # validates that the title is of a specific range of lengths
	validates :description , length: { minimum: 2, maximum: 4096, message: "must be between 2 and 4096 characters long!" }
    # validates that the description is of a length range
	validates :git_link, format: { with: URI.regexp, message: "must be a valid URL link!" }
    # validates that the git link is a real link
	validates :difficulty, numericality: { greater_than: 0, less_than: 6, message: "must be from 1 to 5!" }
    # validates that the difficulty is between 1 and 5

    def self.search(search)
        # checks if the search params exported by the controller are contained by either the title, description, or author field
        where("title ILIKE ? OR description ILIKE ? OR author ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    end

  has_attached_file :background_img, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
    validates_attachment_content_type :background_img, :content_type => /\Aimage\/.*\Z/



  has_attached_file :carousel_img_one, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
    validates_attachment_content_type :carousel_img_one, :content_type => /\Aimage\/.*\Z/




  has_attached_file :carousel_img_two, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
    validates_attachment_content_type :carousel_img_two, :content_type => /\Aimage\/.*\Z/



    has_attached_file :carousel_img_three, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
    validates_attachment_content_type :carousel_img_three, :content_type => /\Aimage\/.*\Z/


end

showme_project/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

include ApplicationHelper 

#runs method to update unapproved articles notification before changing page
before_action :unapproved_number

  def index
    if !current_user
      redirect_to root_path
      # if there is no current user (ie not logged on) then reidrect to home page
    elsif 
      if params[:search]
        @articles = isapproved?(Article.search(params[:search]))
        # if there is a user and they input search params then provide articles containing these using seach (def. in model)
      else
        @articles = current_user.articles
        # otherwise just get the users' own article portfolio
      end
    end
  end

  def show
    @article = Article.find(params[:id])
    # find article with id given in url
    respond_to do | format |
      format.html 
      format.pdf do 
        pdf = ArticlePdf.new(@article)
        # pdf.text @article.title
        # pdf.text @article.description
        send_data pdf.render, type: "application/pdf",
                              disposition: "inline"                 
      end
    end
  end

  def new
    if !current_user
      redirect_to root_path
      # if there is no current user then redirect to home page
    else
      @article = Article.new
      # else create a new object with article class 
    end
  end

  def create
    @article = Article.create(article_params)
    # creates article with protected article parameters
    @article.user_id = current_user.id
    # gives the user id to be that of current user
    @article.author = current_user.name
    # gives author to be that of current user
    @article.approved = false
    # confirms article requires approval from admin
    if @article.save
      redirect_to @article
      # if article save is successful then redirect to that article
    else
      render :new
      # if save fails due to errors then rerender the page
    end

  end

  def edit
    @article = Article.find(params[:id])
    # find article with id given in url
  end

  def update
    @article = Article.find(params[:id])
    # find article with id given in url
    if @article.update(article_params)
      redirect_to @article
      # if article update successful then redirect to that article
    else
      render :edit
      # if update failed due to errors then rerender edit page to fix errors
    end
  end

  def destroy
    Article.destroy(params[:id])
    # delete the article with specific id
    redirect_to articles_url
    # direct to index page
  end


  def approveindex
  # lets the admin view unapproved articles and approve them
   @articles = Article.all.where(approved: false)
  end

  def approveupdate
  # updates the article with an approved value
    @article = Article.find(params[:id])
    @article.approved = true
    @article.save

    redirect_to @article
  end


  protected
  # these methods are not accessible outside the class
  def article_params
    # these are article params used above
    params.require(:article).permit(:title, :description, :background_img, :carousel_img_one, :carousel_img_two, :carousel_img_three, :git_link, :difficulty, :user_id, :additional_image)
    # this pushes the attributes to the article params
  end

end

showme_project/app/helpers/articles_helper.rb
module ArticlesHelper

	def unapproved_number
		$unapproved_number = Article.all.where(approved: false).length
	end

end

showme_project/app/views/articles/_article.html.erb
<div class="col-4">
<div class="article">

<!-- displays the projects title -->
  <div>
    <p class="title-box"><%= article.title %></p>
  </div>

    <div class="bg-image" style="background-image: url('<%="http://showmeportfolio.s3.amazonaws.com" + article.background_img.path %>')">

    <!-- displays the author of the project -->
    <div class="row author-pos">
      <div class="col-4">
        <p class="author-box">By: <%= article.author %></p>
      </div>
      <div class="offset-md-6">
        <!-- link to Homepage/root if the user is on the 'show' page -->
      <%= link_to "Home Page", "/" if action_name == "show" %> 
      <!-- link to 'show page' using the View button unless the user is on the show page -->
      <%= link_to "View", article, :class => 'show-button' unless action_name == "show" %> 
    </div>
    </div>

  </div>






<!-- If user is on show page dispay in if statement  -->
<% if action_name == "show" %>
<!-- display the discription of the project -->
 <p>Description: <strong><%= article.description %></strong></p>
<!-- display the git link for the project -->
 <p>Git Link: <strong><%= article.git_link %></strong></p>
    <br>
  <% end %>



</div>















  <!--  'can can', if user is admin. display buttons to edit and delete the project -->
  <% if can? :update, article %>
    <%= link_to "Edit Page", edit_article_path(article) if action_name == "show" %>
    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" } if action_name == "show" %>
  <% end %>
</div>

showme_project/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<!-- Checks for any validation errors -->
  <h3><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
<!-- displays the number of validation errors on the page -->
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <!-- Actual error message displayed to screen -->
    <% end %>
  </ul>

<% end %>

<div class="col-12 text-center">

<div class='form-body'>
  <%= form_for(@article) do |f| %>
  <!-- form helper which allows whats inputted into the form be pushed into the database -->
    <%= f.label :title, "Title " %>
    <br>
    <%= f.text_field :title, size: 70 %>
    <!-- Title label and title entry field -->
    <br> <br>

    <%= f.label :description, "Description " %> 
    <br>
    <%= f.text_area :description, size: "70x20" %>
    <!-- Description label and Description entry field -->
    <br> <br>

    <%= f.label :background_img, "Background Image" %>
    <br>
    <%= f.file_field :background_img %> 
    <br><br>

    <%= f.label :carousel_img_one, "Image One" %>
    <br>
    <%= f.file_field :carousel_img_one %>
    <br><br>

    <%= f.label :carousel_img_two, "Image Two" %>
    <br>
    <%= f.file_field :carousel_img_two %>
    <br><br>

    <%= f.label :carousel_img_three, "Image Three" %>
    <br>
    <%= f.file_field :carousel_img_three %>
    <br><br>

    <%= f.label :git_link, "GitHub URL " %>
    <br>
    <%= f.text_field :git_link, size: 70 %>
    <!-- GitHub Url label and GitHub Url entry field -->
    <br> <br>



    <%= f.label :difficulty, "Difficulty (1-5) " %>
    <p id='slider-output'><p>
    <div id='slider-dv'>
      <%= f.range_field :difficulty, :min=>1, :max=>5, :value=>1, :class=>"slide", :id=>"slider1"%>
    </div>
    <!-- Difficulty slider which allows the user to chose between a difficulty of 1 and 5 -->
    <br>



    

    <%= f.submit %>
    <!-- Submit button which pushes the information in the form to the database. -->
    <br>

  <% end %>
</div>
</div>

<script>

  var slider = document.getElementById("slider1");
  // Variable that stores the slider
  var output = document. getElementById("slider-output");
  // Variable that stores the output variable
  output.innerHTML = slider.value;
  // Stores the slider value to the output variable
  slider.oninput = function() {
    output.innerHTML = this.value;
  }
  // Function that updates the output variable in real time
</script>
<!-- Script that controls the behaviour of the slider -->

showme_project/app/views/articles/approveindex.html.erb
<div class="col-12">
<h1 class="creation-new-header"> Approval Page </h1>
</div>

<% @articles.each do |article| %>

<div class="col-4 approve-overflow">

	<div class="article">


	<div class="auth-title-box">
	<!-- displays the projects title -->
	  <p class="title-box"><%= article.title %></p>
	</div>

 	<div class="bg-image" style="background-image: url('<%= "http://showmeportfolio.s3.amazonaws.com" + article.background_img.path %>')">
 	<div class="row author-posi">

 	<!-- displays the author of the project -->
	  <p class="author-box">By: <%= article.author %></p>



	  <!-- link to Homepage/root if the user is on the 'show' page -->
	  <%= link_to "Home Page", "/" if action_name == "show" %> 
	  <!-- link to 'show page' using the View button unless the user is on the show page -->
	  <%= link_to "View", article, :class => 'show-button1' unless action_name == "show" %> 



	<!-- If user is on show page dispay in if statement  -->
	  <% if action_name == "show" %>
	<!-- display the discription of the project -->
	    <p>Description: <strong><%= article.description %></strong></p>
	<!-- display the git link for the project -->
	    <p>Git Link: <strong><%= article.git_link %></strong></p>
	    <br>
	  <% end %>



	  


	  <!--  'can can', if user is admin. display buttons to edit and delete the project -->
	  <% if can? :update, article %>

	    <%= link_to "Edit Page", edit_article_path(article) if action_name == "show" %>
	    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" } if action_name == "show" %>
	  <% end %>


	</div>




 	</div>







	




	</div>

</div>

<% end %>

showme_project/app/views/articles/edit.html.erb
<% if can? :create, @article %>
<!-- Checks to see if current user is an admin using cancan -->
<h1 class= 'creation-new-header'> Edit Article </h1>

<br>
<br>
  <%= render "form" %>
  <!-- render ERB which presents the form partial to the page -->
<% else %>
  <h1> ACCESS DENIED </h1>
  <!-- if the current user is not an admin they are presented with this message -->
<% end %>

showme_project/app/views/articles/index.html.erb
<% if @articles.present? %>
<!-- Checks to see if the article exsists -->
  <%= render @articles %>
  <!-- ERB that renders the article partial to the page -->
<% else %>
  <div class="sad-box-div">
	  <p class="sad-box">There are no articles containing the term(s) <%= params[:search] %>!</p>
	  <!-- If the article does not exist they are presented with a a message saying so -->
  </div>
<% end %>

<% unapproved_number %>

showme_project/app/views/articles/new.html.erb
<h1 class= 'creation-new-header'> New Article </h1>

<br>
<br>
<%= render 'form' %>

showme_project/app/views/articles/show.html.erb
		<div class="col-12 title-wrapper">
			<div class="col-12 show-title">
		<h1 class="title-box-text"><%= @article.title %></h1>
			</div>
		</div>  






	<div class="container">
	<div class="carousel">
		<input type="radio" id="carousel-1" name="carousel[]" checked>
		<input type="radio" id="carousel-2" name="carousel[]">
     <input type="radio" id="carousel-3" name="carousel[]">
		<input type="radio" id="carousel-4" name="carousel[]">
		<ul class="carousel__items">
			<li class="carousel__item"><%= image_tag "http://showmeportfolio.s3.amazonaws.com"+ @article.carousel_img_one.path %>></li>
			<li class="carousel__item"><img <%= image_tag "http://showmeportfolio.s3.amazonaws.com"+ @article.carousel_img_two.path %> alt=""></li>
			<li class="carousel__item"><img <%= image_tag "http://showmeportfolio.s3.amazonaws.com"+ @article.carousel_img_three.path %> alt=""></li>
			<li class="carousel__item"><img <%= image_tag "http://showmeportfolio.s3.amazonaws.com"+ @article.background_img.path %> alt=""></li>
		</ul>
     <div class="carousel__prev">
     	<label for="carousel-1"></label>
     	<label for="carousel-2"></label>
     	<label for="carousel-3"></label>
     	<label for="carousel-4"></label>
     </div>
     <div class="carousel__next">
       <label for="carousel-1"></label>
       <label for="carousel-2"></label>
       <label for="carousel-3"></label>
       <label for="carousel-4"></label>
     </div>
     <div class="carousel__nav">
       <label for="carousel-1"></label>
       <label for="carousel-2"></label>
       <label for="carousel-3"></label>
       <label for="carousel-4"></label>
     </div>
   </div>
 </div>



	


	<div class="col-10 offset-md-1">
		<% if action_name == "show" %>
			<p class="show-description-text">
				<strong>
					<%= markdown @article.description %>
				</strong>
			</p>
			<br>
		<% end %>
	</div>





		<div class="col-4 links"> <p class="show-author"><strong>Created by:</strong> <%= @article.author %></p></div>
		<div class="col-4 links"> <p class="show-author"><strong>Project difficulty:</strong> <%= @article.difficulty %></p></div>
		<div class="col-4 links"> <p class="show-author"><strong> <a href="<%= @article.git_link %>" class="button">Go To GitHub<i class="fa fa-github" aria-hidden="true"></i></a></strong></p></div>  


	<div class="col-12">

		<div class="col-4 offset-md-1 inline-block">
			<p> <%= link_to "View PDF", article_path(@article, format: "pdf"), :class => 'button' %> </p>
		</div>

	<div class="col-6 offset-md-2">

	<div class="show-buttons">

		<%= link_to "Home Page", "/" if @action_name == "show" %> 
		<%= link_to "View", @article, :class => 'show-button' unless action_name == "show" %> 
		<% if can? :update, @article %>
			<%= link_to "Edit Page", edit_article_path(@article), :class => 'button' if action_name == "show" %>
			<%= link_to "Delete", article_path(@article), method: :delete, :class => 'button', data: { confirm: "Are you sure?" } if action_name == "show" %>
	    <% if @article.approved == false %>
	      <%= link_to "Approve", "/articles/approve/#{@article.id}", method: :put, :class => 'button', data: { confirm: "Are you sure you wish to approve this article?"} if action_name == "show" %>
	    <% end %>
		<% end %>


	</div>
	</div>

<div id="social-media-div">

	<a href="https://www.facebook.com/sharer/sharer.php?u=http%3A//localhost%3A3000/articles/<%= @article.id %>" target="_blank">
		<div id="facebook-button" class="social-media-buttons"></div>
	</a>

	<a href="https://www.linkedin.com/shareArticle?mini=true&url=http://localhost:3000/articles<%= @article.id %>&title=ShowMe%20Portfolio%20Project&summary=Portfolio%20item%20<%= @article.id %>&source=LinkedIn" target="_blank">
		<div id="linkedin-button" class="social-media-buttons"></div>
	</a>

	<a href="https://twitter.com/intent/tweet?original_referer=http%3A%2F%2Flocalhost%3A3000%2Farticles%2F1&ref_src=twsrc%5Etfw&text=ShowmeProject&tw_p=tweetbutton&url=http%3A%2F%2Flocalhost%3A3000%2Farticles%2F<%= @article.id %>" target="_blank">
		<div id="twitter-button" class="social-media-buttons"></div>
	</a>

</div>